In [ ]:
import torch

torch.cuda.is_available()
# torch.cuda.is_tf32_supported()
# torch.cuda.is_bf16_supported()

True


True

In [ ]:
torch.tensor(1) # 0-D, scalar

tensor(1)

In [ ]:
torch.tensor([1,2,3]) # 1-D, vector

tensor([1, 2, 3])

In [6]:
torch.tensor([[1,2], [3,4]]) # 2-D, matrix

tensor([[1, 2],
        [3, 4]])

In [7]:
torch.tensor([[[1,2], [3,4],
                [5,6], [7,8]]]) # 3-D

tensor([[[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]])

### Tensor Data types

- `.dtype`

In [8]:
tensor1d = torch.tensor([1,2,3])
print(tensor1d.dtype)

torch.int64


it is possible to change the precision using a tensor’s `.to` method. The following code demonstrates this by changing a 64-bit integer tensor into a 32-bit float tensor:

In [9]:
floatvec = tensor1d.to(torch.float32)
print(floatvec.dtype)

torch.float32


## Common PyTorch tensor Operations

### shape

In [10]:
# shape

tensor2d = torch.tensor([[1,2,3],
                         [5,6,7]])
print(tensor2d)

tensor([[1, 2, 3],
        [5, 6, 7]])


In [11]:
print(tensor2d.shape)

torch.Size([2, 3])


### `reshape()`

In [12]:
print(tensor2d.reshape(3,2))

tensor([[1, 2],
        [3, 5],
        [6, 7]])


### `view()`

In [13]:
print(tensor2d.view(3, 2))

tensor([[1, 2],
        [3, 5],
        [6, 7]])


In [14]:
print(tensor2d.T)

tensor([[1, 5],
        [2, 6],
        [3, 7]])


### Matrix Multiplication

`.matmul`

In [15]:
print(tensor2d.matmul(tensor2d.T))

tensor([[ 14,  38],
        [ 38, 110]])


# Logistic Regression Forward Pass

In [4]:
import torch.nn.functional as F
import torch

In [5]:
y = torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([2.0])
b = torch.tensor([0.0])

In [10]:
z = x1 * w1 + b
z

tensor([2.2000])

In [9]:
a = torch.sigmoid(z)
a

tensor([0.9002])

In [11]:
loss = F.binary_cross_entropy(a, y)
loss

tensor(0.1051)

### Computing Gradients via autograd

In [12]:
import torch.nn.functional as F
from torch.autograd import grad

In [13]:
y = torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([2.2], requires_grad=True)
b = torch.tensor([0.0], requires_grad=True)

In [14]:
z = x1 * w1 + b

In [15]:
a = torch.sigmoid(z)

In [16]:
loss = F.binary_cross_entropy(a, y)

In [17]:
grad_L_w1 = grad(loss, w1, retain_graph=True)

In [18]:
grad_L_b = grad(loss, b, retain_graph=True)

In [19]:
grad_L_w1

(tensor([-0.0898]),)

In [20]:
grad_L_b

(tensor([-0.0817]),)

In [21]:
# calling backward on loss, pytorch computes the gradients of all the leaf nodes in the graph which will be stored via the tensors' `.grad` attribute

loss.backward()

In [22]:
w1.grad

tensor([-0.0898])

In [23]:
b.grad

tensor([-0.0817])